# Generated by Django 6.0.4 on 2026-04-30 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Laden',
                'verbose_name_plural': 'Läden',
                'ordering': ['reihenfolge', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Einkauf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel', models.CharField(max_length=200, verbose_name='Artikel')),
                ('gekauft', models.BooleanField(default=False, verbose_name='Gekauft')),
                ('geaendert', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='einkäufe', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('laden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='einkäufe', to='shopping.laden', verbose_name='Laden')),
            ],
            options={
                'verbose_name': 'Einkauf',
                'verbose_name_plural': 'Einkäufe',
                'ordering': ['laden__reihenfolge', 'laden__name', 'artikel'],
            },
        ),
    ]
