# Generated by Django 4.2.30 on 2026-05-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='einkauf',
            options={'ordering': ['reihenfolge'], 'verbose_name': 'Einkauf', 'verbose_name_plural': 'Einkäufe'},
        ),
        migrations.AddField(
            model_name='einkauf',
            name='reihenfolge',
            field=models.PositiveIntegerField(default=0, verbose_name='Reihenfolge'),
        ),
    ]
